# Config for SimplyTAB

tab:
  header:
    - 'My Super Cool Server'
    - ''
    - 'Server: <bold><white><mc-version> </white><red>|</red></bold><reset> Players: <bold><white><online-count> </white><red>|</red></bold><reset> TPS: <bold><white><tps></white></bold>'
    - ''
  footer:
    - ''
    - ''
    - '<green>YOUR SERVER</green>'
  tps:
    '20': '<green>20.0</green>'
    '19': '<green>20.0*</green>'
    '18': '<green>20.0*</green>'
    '*': '<red>%value%</red>'

sorting:
  - type: 'index'
    placeholder: '<primary_rank>'
    values:
      - Owner
      - Admin
      - Mod
      - JrMod
      - Donator
      - default

  - type: 'alphabetical'
    placeholder: '<player_displayname>'

group-prefix: ''
group-suffix: ''
group-player-color: ''
tab-displayname: '<player_displayname>'
